# Generated by Django 3.0 on 2022-04-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share2', '0007_alter_ip_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='filelist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails2',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
